[versions]

android-compile = "36"
android-target = "36"
android-desugarjdklibs = "2.1.5"
android-gradle = "9.0.0"
android-min = "26"
androidx-activity = "1.12.2"
androidx-annotations = "1.9.1"
androidx-compose-runtime = "1.10.1"
androidx-compose-ui = "1.10.1"
androidx-compose-foundation = "1.10.1"
androidx-compose-material = "1.4.0"
androidx-core = "1.17.0"
androidx-lifecycle = "2.10.0"
coroutines = "1.10.2"
dependency-analysis = "3.5.1"
fgp = "0.36.3"
java-target = "11"
java-toolchain = "21"
khonshu = "0.34.4"
ksp = "2.3.4"
kotlin = "2.3.0"
metro = "0.9.4"
timber = "5.0.1"

[libraries]
android-desugarjdklibs = { module = "com.android.tools:desugar_jdk_libs", version.ref = "android-desugarjdklibs" }
androidx-activity = { module = "androidx.activity:activity", version.ref = "androidx-activity" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }
androidx-annotations = { module = "androidx.annotation:annotation", version.ref = "androidx-annotations" }
androidx-compose-runtime = { module = "androidx.compose.runtime:runtime", version.ref = "androidx-compose-runtime" }
androidx-compose-ui = { module = "androidx.compose.ui:ui", version.ref = "androidx-compose-ui" }
androidx-compose-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "androidx-compose-foundation" }
androidx-compose-material = { module = "androidx.compose.material3:material3", version.ref = "androidx-compose-material" }
androidx-core = { module = "androidx.core:core-ktx", version.ref = "androidx-core" }
androidx-lifecycle-common = { module = "androidx.lifecycle:lifecycle-common", version.ref = "androidx-lifecycle" }
androidx-lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel", version.ref = "androidx-lifecycle" }
androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "androidx-lifecycle" }
androidx-lifecycle-viewmodel-savedstate = { module = "androidx.lifecycle:lifecycle-viewmodel-savedstate", version.ref = "androidx-lifecycle" }
coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
khonshu-navigation = { module = "com.freeletics.khonshu:navigation", version.ref = "khonshu" }
khonshu-codegen-compiler = { module = "com.freeletics.khonshu:codegen-compiler", version.ref = "khonshu" }
khonshu-codegen-runtime = { module = "com.freeletics.khonshu:codegen-runtime", version.ref = "khonshu" }
khonshu-statemachine = { module = "com.freeletics.khonshu:state-machine", version.ref = "khonshu" }
kotlinx-serialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version = "1.10.0" }
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }

[plugins]
android-application = { id = "com.android.application", version.ref = "android-gradle" }
dependency-analysis = { id = "com.autonomousapps.dependency-analysis", version.ref = "dependency-analysis" }
fgp-app = { id = "com.freeletics.gradle.app.android", version.ref = "fgp" }
fgp-feature = { id = "com.freeletics.gradle.feature", version.ref = "fgp" }
fgp-nav = { id = "com.freeletics.gradle.nav", version.ref = "fgp" }
fgp-root = { id = "com.freeletics.gradle.root", version.ref = "fgp" }
kotlin = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
metro = { id = "dev.zacsweers.metro", version.ref = "metro" }
